# Generated by Django 4.0.1 on 2022-02-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_alter_idea_related'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-date_posted']},
        ),
    ]
