# Generated by Django 4.0.1 on 2022-02-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imga',
            new_name='image',
        ),
    ]
